apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manasikoli/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "mysql+pymysql://user:password@db:3306/userdb"
